### ISSUE TITLE
php8+  with-curl option didn`t work

### ISSUE THREAD

**Issue by visonforcoding** [php/doc-zh#172]
From manual page: https://php.net/curl.installation

---
![image](https://user-images.githubusercontent.com/4387302/149258433-0e0c7281-ab2f-4113-b258-1b51871c7c9d.png)

specified curl-dir , still make default dir.

the Makefile `CURL_SHARED_LIBADD` is  empty
`CURL_SHARED_LIBADD = `

after make

the `CURL` is still old version

**Comment by shiny** [comment]
https://github.com/php/php-src/issues/7938
