### ISSUE TITLE
touch时间戳问题

### ISSUE THREAD

**Issue by babaiyun** [php/doc-zh#208]
From manual page: https://php.net/function.touch

touch在win10环境下，先复制文件后，修改文件最后修改日期，结果修改后文件的实际时间戳多1秒。这个问题是在文件同步到U盘的情况下出现的，在系统磁盘之间无问题。
---
$dfile ='D:\\touch_test\\100.txt';
$efile ='E:\\upan_disk\\100.txt';

$dfile =str_replace('\\', '/', $dfile);
$efile =str_replace('\\', '/', $efile);

$mt_from =filemtime($dfile);

var_dump( 'dfile: '. $mt_from );
var_dump( 'efile: '. filemtime($efile) );

$stat =copy($dfile, $efile);
var_dump( $stat );

$stat =touch($efile, $mt_from);
var_dump( $stat );

**Comment by mowangjuanzi** [comment]
你检查一下你的U盘格式。这个问题主要是在Fat32中存在。

参考：https://www.zhihu.com/question/21747929/answer/239575235

**Comment by babaiyun** [comment]
确实，没想到是磁盘格式问题，非常感谢！
