### ISSUE TITLE
大海捞针，在大海（haystack）中搜索针（ needle）

### ISSUE THREAD

**Issue by dawaer** [php/doc-zh#223]
From manual page: https://php.net/function.in-array

---
这句还是翻译成，比较合适：
大海捞针，在干草堆（haystack）中搜索针（ needle）

**Comment by tianyiw2013** [comment]
大海捞针，好记易懂，不建议修改成干草堆。

**Comment by mowangjuanzi** [comment]
这事是我干的。谁能帮我改回去...
