### ISSUE TITLE
从官网中下载下来的chm文件类似渲染缺失

### ISSUE THREAD

**Issue by r1ght0us** [php/doc-zh#350]
![image](https://user-images.githubusercontent.com/30382389/191674761-cc4b65c4-d1ea-498e-865c-63dfe0d218a2.png)
之前下载的chm帮助文件有明显的蓝色主题，但是现在变成了纯白，请问是我设置的有问题还是类似渲染缺失？

**Comment by mowangjuanzi** [comment]
这个问题建议去英文项目那边提交。该项目不负责 chm 文件的生成。

**Comment by r1ght0us** [comment]
@mowangjuanzi 谢谢，我关闭这个issue了
