### ISSUE TITLE
When the value is negative, the return value is incorrect

### ISSUE THREAD

**Issue by playadmin** [php/doc-zh#434]
From manual page: https://php.net/pdo.lastinsertid

When the return value should be -1,
but 18446744073709551615 is returned
only in php8.1

**Comment by mowangjuanzi** [comment]
我仔细看了一下该文档。该文档在任何情况下，都不会返回 -1 。请问你觉得应该是在什么情况下，会返回 -1 呢？

**Comment by playadmin** [comment]
当指定插入数据的主键是-1的时候

**Comment by mowangjuanzi** [comment]
我去追了一下源码。可能还真是 PHP 的 bug。可以看这里的代码：

https://github.com/php/php-src/blob/master/ext/pdo_mysql/mysql_driver.c#L292

```c
/* {{{ pdo_mysql_last_insert_id */
static zend_string *pdo_mysql_last_insert_id(pdo_dbh_t *dbh, const zend_string *name)
{
	pdo_mysql_db_handle *H = (pdo_mysql_db_handle *)dbh->driver_data;
	PDO_DBG_ENTER("pdo_mysql_last_insert_id");
	PDO_DBG_RETURN(zend_u64_to_str(mysql_insert_id(H->server)));
}
/* }}} */
```

`zend_u64_to_str`。问题主要在这里。它默认将其认为是 `unsigned long int`。实际上这个返回值既有可能是 `unsigned long int` 也有可能是 `long int` 。既然是你发现的，我觉得你可以跟官方报告下这个问题。如果不方便，我也可以代为提交。😀

**Comment by playadmin** [comment]
嗯明显是把有符号的也当作无符号返回了。
那就麻烦你提交吧~

**Comment by mowangjuanzi** [comment]
https://github.com/php/php-src/issues/9811 可以看一下这里的讨论
