### ISSUE TITLE
the item "serialize_precision" is now default 17 not -1; Prior to PHP 7.1.0, the default value was -1.

### ISSUE THREAD

**Issue by crazy-boy** [php/doc-zh#469]
From manual page: https://php.net/ini.core

---

**Comment by mowangjuanzi** [comment]
所以问题是？

**Comment by mowangjuanzi** [comment]
https://github.com/php/php-src/blob/master/main/main.c#L704 

可以看到这里的代码。注册的就是 -1 没啥问题啊

**Comment by sy-records** [comment]
https://3v4l.org/ZETkv
https://3v4l.org/ZETkv#v7.0.33
