### ISSUE TITLE
a small translation mistake

### ISSUE THREAD

**Issue by ipukio** [php/doc-zh#51]
From manual page: https://php.net/language.oop5.basic
language:Chinese(Simplified)

![image](https://user-images.githubusercontent.com/64894096/123360571-1e041600-d5a0-11eb-815d-3d265785e71d.png)

Calling a non-static method statically throws an Error. 翻译成了以静态方式去调用一个静态方法
应该改成 :以静态方式去调用一个非静态方法

---

**Comment by sy-records** [comment]
Thank you for your feedback.
