### ISSUE TITLE
openssl_pkey_get_details 未知类型返回值说明错误

### ISSUE THREAD

**Issue by hankzzhang** [php/doc-zh#519]
From manual page: https://php.net/function.openssl-pkey-get-details

---

中文文档 :
type (如下密钥类型之一： OPENSSL_KEYTYPE_RSA, OPENSSL_KEYTYPE_DSA, OPENSSL_KEYTYPE_DH, OPENSSL_KEYTYPE_EC 或者 未知类型返回1)

英语文档: 
type (type of the key which is one of OPENSSL_KEYTYPE_RSA, OPENSSL_KEYTYPE_DSA, OPENSSL_KEYTYPE_DH, OPENSSL_KEYTYPE_EC or -1 meaning unknown).

更正：
未知类型返回1 => 未知类型返回 -1

**Comment by shiny** [comment]
感谢指出错误
