### ISSUE TITLE
示例9中文翻译有误

### ISSUE THREAD

**Issue by Eric688** [php/doc-zh#643]
From manual page: https://php.net/language.namespaces.faq

---示例 #9 在双引号字符串中使用命名空间的危险性

<?php
**_$a = new "dangerous\name"; // 在双引号字符串中，\n 是换行符！——这里多了一个‘new’；_**
$obj = new $a;

$a = new 'not\at\all\dangerous'; // 这里没有问题
$obj = new $a;
?>

**Comment by mowangjuanzi** [comment]
能否展开说下？具体指的是哪个错误
？
