### ISSUE TITLE
example function importer issue

### ISSUE THREAD

**Issue by ZhuFrankie** [php/doc-zh#79]
From manual page: https://php.net/generator.send

---
Example (note the handling of null, which you would send to the generator to handle stragglers after the previous batch)

```php
function importer()
{
  $max = 500;
  $items = [];
  while (true) {
    $item = yield;
    if ($item !== null) {
      $items[] = yield;  //$item instead of yield,otherwise the $items will always have one item
    }
    if ($item === null || count($items) >= $max) {
       // do batch operations
       $items = [];
    }
  }
}
```

**Comment by sy-records** [comment]
这里只是一个注释，按照PHP官方的[说明](https://www.php.net/manual/add-note.php?sect=generator.send&redirect=https://www.php.net/manual/zh/generator.send.php)，代码协作或改进可以不用修改，可以在其他地方进行发布
