### ISSUE TITLE
属性的访问控制页面中执行结果展示错误

### ISSUE THREAD

**Issue by 1402113092** [php/doc-zh#80]
From manual page: https://php.net/language.oop5.visibility

---属性的访问控制
MyClass2类继承MyClass时,在MyClass2类中修改public和protected属性,对应属性会发生变化,但是手册上的打印结果时错的

$obj2->printHello(); // 输出 Public、Protected2 和 Undefined

输出结果应该是 Public2

**Comment by sy-records** [comment]
感谢反馈，已修正
