### ISSUE TITLE
英文文档更新了，但是待翻译文档列表中并没有出现该文档

### ISSUE THREAD

**Issue by mowangjuanzi** [php/doc-zh#83]
比如该文件的更新历史：

https://github.com/php/doc-en/commits/master/appendices/migration80/other-changes.xml

已经有4次更新。但是[中文版的地址commit](https://github.com/php/doc-zh/blob/master/appendices/migration80/other-changes.xml)却是英文的版本的第一次的 commit 。按照这个情况来说，待翻译文档应该会提示该文档后续有更新。应该进行提示才对呀。

难道说这个只能提示中文没有翻译的吗？😓

**Comment by shiny** [comment]
你在哪看到的“待翻译文档” 😂

**Comment by shiny** [comment]
这个 revision 是用于追踪变化部分，可以用一些工具检查 `4c41f6fa0ebe4afe8b7a3468e7e26dfd0c0e4131 ` 与 `d7a2a4e3f7114ec8f0a71da90ed7e55b70fb77ec ` 的差别，提升翻译效率。

目前没看到有自动化工具去做提醒（以前使用 svn 的时候有）

**Comment by mowangjuanzi** [comment]
http://doc.php.net/revcheck.php?p=missfiles&lang=zh

我都是根据这个链接的内容来知道是那些需要翻译的

**Comment by sy-records** [comment]
这个链接是**未翻译**的内容，你查看的内容是翻译过的，可以查看 http://doc.php.net/revcheck.php?dir=appendices%2Fmigration80&p=files&lang=zh
