### ISSUE TITLE
ksort sorting is inconsistent

### ISSUE THREAD

**Issue by ClassmateLin** [php/doc-zh#837]
From manual page: https://php.net/function.ksort

---
php7
```
$data = [ "user_id" => 1, "0"=>1 ]; 
ksort($data);
var_dump($data);
```
result:
```
array(2) {
  'user_id' =>int(1)
  [0] =>int(1)
}
```

php8:
```
$data = [ "user_id" => 1, "0"=>1 ]; 
ksort($data);
var_dump($data);
```
result:
```
array(2) {
  [0] =>int(1)
  'user_id' => int(1)
}
```

**Comment by sy-records** [comment]
Note that ksort will NOT help you much if numeric and string keys are mixed together.

see https://3v4l.org/G6sF5

<img width="1052" alt="image" src="https://github.com/php/doc-zh/assets/33931153/ab3c3fae-fc21-4d14-8f84-886f36e6398b">
