### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by bynow2code** [php/doc-zh#858]
From manual page: https://php.net/function.defined

---

原文：
此函数也可以跟[累常量](https://www.php.net/manual/zh/language.oop5.constants.php)和 [enum cases](https://www.php.net/manual/zh/language.types.enumerations.php) 一起工作。

正确为：
此函数也可以跟[类常量](https://www.php.net/manual/zh/language.oop5.constants.php)和 [enum cases](https://www.php.net/manual/zh/language.types.enumerations.php) 一起工作。

**Comment by sy-records** [comment]
感谢反馈
