### ISSUE TITLE
翻译不准确

### ISSUE THREAD

**Issue by Eno-CN** [php/doc-zh#886]
From manual page: https://php.net/function.is-float

---
**原文**
To test if a variable is a number or a numeric string (such as form input, which is always a string),

**原翻译**
测试变量是数字还是数字字符串（如表单输入，始终是字符串），

**正确翻译**
测试变量是数字或数字字符串（如表单输入，始终是字符串），

**说明**
_or_ 在这里表达的应该是“或”。也可以参考与函数[is_int](https://www.php.net/manual/zh/function.is-int.php)文档的中文翻译保持一致。

**Comment by mowangjuanzi** [comment]
我查询了一下`还是`和`或者`的区别，他们的意思是相同的，但是`还是`多用于疑问句中，而`或者`多用于叙述句中。但是从这里的意思来说，这两个词其实不都合适。

我又仔细看了一下相关文档。按照文档的理解来说，这里的 `is_numeric` 的意思是可以使用该函数测试变量shifo数字以及数字字符串。而我这里的意思变成了使用 `is_numeric` 用来区分数字和数字字符串了。

我晚上再斟酌下，看看如何进行修改。如果你对我的想法有不同见解，可以再沟通。

**Comment by sy-records** [comment]
用或就行，和 is_numberic 的说明一致。

**Comment by Eno-CN** [comment]
> 我查询了一下`还是`和`或者`的区别，他们的意思是相同的，但是`还是`多用于疑问句中，而`或者`多用于叙述句中。但是从这里的意思来说，这两个词其实不都合适。
> 
> 我又仔细看了一下相关文档。按照文档的理解来说，这里的 `is_numeric` 的意思是可以使用该函数测试变量shifo数字以及数字字符串。而我这里的意思变成了使用 `is_numeric` 用来区分数字和数字字符串了。
> 
> 我晚上再斟酌下，看看如何进行修改。如果你对我的想法有不同见解，可以再沟通。

你好，这个地方我理解的是逻辑用语 `或`，表示“任意满足其一”，原文的 `or` 在这可能也是个逻辑用词，如果跳脱出这个语境去理解可能会产生歧义。

“还是”不属于标准的逻辑用语，语义上可能会更倾向于表选择，这个地方会更容易理解为是去区分数字还是数字字符串。

**Comment by Eno-CN** [comment]
另外，再补充一下（可能有点钻牛角尖😁）

如果把“变量是数字或数字字符串”看做是**命题**（逻辑学指表达判断的语言形式）。

这个地方可以把上面的命题拆成两个命题：
- 变量是数字。
- 变量是数字字符串。
把这两个命题用逻辑关系“或”连接起来就是原命题。
