### ISSUE TITLE
php7.4版本对于openssl的版本支持问题

### ISSUE THREAD

**Issue by lsx1205** [php/doc-zh#954]
目前我们使用php7.4版本，但是openssl是3.x的，我们要使用SHA1算法进行验签，在openssl配置中开启leagcy，以让它支持SHA1算法，但是在实际使用中，验签会失败报错。

**Comment by sy-records** [comment]
文档不处理该问题，如果确认是 Bug，可以使用英文和可重现的代码，去 php-src 提交 issue。
